### ISSUE TITLE
unexpected keyword argument 'node_function'

### ISSUE THREAD

**Issue by TobiBu** [ytree-project/ytree#117] opened 2021-11-16 10:31 UTC
### Bug report

**unexpected keyword argument 'node_function' when trying to modify the node appearance in TreePlot**

**Code for reproduction**

```python
p = ytree.TreePlot(a[0], dot_kwargs={'rankdir': 'BT'}, node_function=my_node)
```

**Actual outcome**

```
In [22]: p = ytree.TreePlot(a[0], dot_kwargs={'rankdir': 'BT'}, node_function=my_node)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-ab777a6313c0> in <module>
----> 1 p = ytree.TreePlot(a[0], dot_kwargs={'rankdir': 'BT'}, node_function=my_node)

TypeError: __init__() got an unexpected keyword argument 'node_function'
```

I am using tree version 2.3.

**Comment by brittonsmith** [comment] 2021-11-17 10:46
Hi there, does this problem go away with `ytree` 3.0 or later?

**Comment by brittonsmith** [comment] 2021-11-26 16:29
Hi @TobiBu, are you able to try this out with a later version of ytree? If so, I'm happy to try and fix it if there is still a problem. If this issue is only for an older version of ytree, then I think you'll have to update to a later version.

**Comment by brittonsmith** [comment] 2021-12-01 13:59
I can confirm that the `node_function` keyword was not added until after the 2.3.0 release. Since we've moved onto ytree-3.x, I'm no longer going to update the 2.x series. I'm going to close this for now, but feel free to reopen if I've misunderstood something or there is more you'd like to add.

**Closed by brittonsmith** 2021-12-01 13:59 UTC
